CREATE TABLE VEICULO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	MARCA VARCHAR(100),
	MODELO VARCHAR(100),
	DT_FABRICACAO DATE,
	VL_CONSUMO_CIDADE DECIMAL(20,2),
	VL_CONSUMO_RODOVIA DECIMAL(20,2)
);